macro(build_dealii)
  cmake_policy(SET CMP0074 NEW) #use _ROOT in find package!
  set(oneValueArgs VERSION)
  cmake_parse_arguments(BUILD_DEALII "" "${oneValueArgs}" "" ${ARGN})
  
  if (NOT BUILD_DEALII_VERSION)
    set(BUILD_DEALII_VERSION "9.4.0")
  endif()
  
  string(REPLACE "." ";" TMPLIST ${BUILD_DEALII_VERSION})
  list(GET TMPLIST 0 BUILD_DEALII_MAJOR_VERSION)
  list(GET TMPLIST 1 BUILD_DEALII_MINOR_VERSION)
  
  #Sundials only works with newer deal.II version (>=9.1.0)
  if(DEFINED BUILD_SUNDIALS_VERSION)
    if(BUILD_DEALII_MAJOR_VERSION STRGREATER_EQUAL "9" AND BUILD_DEALII_MINOR_VERSION STRGREATER_EQUAL "1")
      list(APPEND DEALII_DEPENDENCIES "sundials")
      list(APPEND DEALII_CONFOPTS "-D DEAL_II_WITH_SUNDIALS:BOOL=ON")
      list(APPEND DEALII_CONFOPTS "-D SUNDIALS_DIR=${sundials_DIR}")
    else()
      list(APPEND DEALII_CONFOPTS "-D DEAL_II_WITH_SUNDIALS:BOOL=OFF")
    endif()
  endif()
  
  
  string(CONCAT BUILD_DEALII_REPO "https://github.com/dealii/" "dealii.git")
  string(CONCAT BUILD_DEALII_TAG "v" ${BUILD_DEALII_VERSION})
  
  if(DEFINED BOOST_DIR)
    list(APPEND DEALII_CONFOPTS "-D BOOST_DIR=${BOOST_DIR}")
    else()
  endif()
  build_cmake_git_subproject(
    NAME dealii-${BUILD_DEALII_VERSION}
    VERSION "in_name"
    GIT_REPO ${BUILD_DEALII_REPO}
    GIT_TAG ${BUILD_DEALII_TAG}
    DOWNLOAD_ONLY ${DOWNLOAD_ONLY}
    BUILD_ARGS
      -D CMAKE_BUILD_TYPE=DebugRelease
      -D BUILD_SHARED_LIBS:BOOL=ON
      -D DEAL_II_WITH_MPI:BOOL=ON 
      -D DEAL_II_COMPONENT_DOCUMENTATION:BOOL=OFF 
      -D DEAL_II_WITH_LAPACK:BOOL=ON
      -D LAPACK_LIBRARIES=${BLAS_LIBS}
      -D BOOST_DIR=${BOOST_DIR}
      -D DEAL_II_WITH_UMFPACK:BOOL=ON
      -D DEAL_II_FORCE_BUNDLED_UMFPACK:BOOL=OFF 
      -D DEAL_II_WITH_BOOST:BOOL=ON 
      -D DEAL_II_FORCE_BUNDLED_BOOST:BOOL=OFF 
      -D DEAL_II_WITH_ZLIB:BOOL=ON
      -D DEAL_II_COMPONENT_EXAMPLES:BOOL=ON
      -D CMAKE_POLICY_DEFAULT_CMP0057:STRING=NEW 
      -D CMAKE_POLICY_DEFAULT_CMP0074:STRING=NEW
      ${DEALII_CONFOPTS}
  )

  list(APPEND DEALII_VERSIONS ${BUILD_DEALII_VERSION})
endmacro()