macro(build_ginkgo)
  set(oneValueArgs VERSION)
  cmake_parse_arguments(BUILD_GINKGO "" "${oneValueArgs}" "" ${ARGN})
  
  if (NOT BUILD_GINKGO_VERSION)
    set(BUILD_GINKGO_VERSION "1.4.0")
  endif()
  
  string(CONCAT BUILD_GINKGO_REPO "https://github.com/ginkgo-project/" "ginkgo.git")
  string(CONCAT BUILD_GINKGO_TAG "v" ${BUILD_GINKGO_VERSION})
  
  build_cmake_git_subproject(
    NAME ginkgo
    DOWNLOAD_ONLY ${DOWNLOAD_ONLY}
    VERSION ${BUILD_GINKGO_VERSION}
    GIT_REPO ${BUILD_GINKGO_REPO}
    GIT_TAG ${BUILD_GINKGO_TAG}
    BUILD_ARGS
      -D BUILD_SHARED_LIBS:BOOL=ON 
      -D GINKGO_BUILD_TESTS:BOOL=OFF 
      -D GINKGO_FAST_TESTS:BOOL=OFF 
      -D GINKGO_BUILD_EXAMPLES:BOOL=OFF 
      -D GINKGO_BUILD_BENCHMARKS:BOOL=OFF 
      -D GINKGO_BENCHMARK_ENABLE_TUNING:BOOL=OFF 
      -D GINKGO_BUILD_DOC:BOOL=OFF 
      -D GINKGO_VERBOSE_LEVEL=1 
      -D GINKGO_DEVEL_TOOLS:BOOL=OFF 
      -D GINKGO_WITH_CLANG_TIDY:BOOL=OFF 
      -D GINKGO_WITH_IWYU:BOOL=OFF 
      -D GINKGO_CHECK_CIRCULAR_DEPS:BOOL=OFF 
      -D GINKGO_WITH_CCACHE:BOOL=OFF 
      -D GINKGO_BUILD_HWLOC:BOOL=OFF
  )

  list(APPEND DEALII_DEPENDENCIES "ginkgo")
  list(APPEND DEALII_CONFOPTS "-D DEAL_II_WITH_GINKGO:BOOL=ON")
  list(APPEND DEALII_CONFOPTS "-D GINKGO_DIR=${ginkgo_DIR}")
endmacro()