macro(build_scalapack)

  set(oneValueArgs VERSION)
  cmake_parse_arguments(BUILD_SCALAPACK "" "${oneValueArgs}" "" ${ARGN})

  if(${INSTALL_reference_scalapack})
    if( NOT BUILD_SCALAPACK_VERSION )
      set(BUILD_SCALAPACK_VERSION "2.1.0")
    endif()
    set(BUILD_SCALAPACK_C_FLAGS "-g -fPIC -O3")
    set(BUILD_SCALAPACK_F_FLAGS "-fallow-argument-mismatch")
    
    string(CONCAT BUILD_SCALAPACK_REPO "https://github.com/Reference-ScaLAPACK/" "scalapack.git")
    string(CONCAT BUILD_SCALAPACK_TAG "v" ${BUILD_SCALAPACK_VERSION})
  elseif(${INSTALL_amd_scalapack})
  
  endif()

  build_cmake_git_subproject(
    NAME ScaLAPACK
    VERSION ${BUILD_SCALAPACK_VERSION}
    GIT_REPO ${BUILD_SCALAPACK_REPO}
    GIT_TAG ${BUILD_SCALAPACK_TAG}
    DOWNLOAD_ONLY ${DOWNLOAD_ONLY}
    BUILD_ARGS
      -D BUILD_SHARED_LIBS:BOOL=ON
      -D CMAKE_C_COMPILER=${CMAKE_MPI_C_COMPILER}
      -D CMAKE_Fortran_COMPILER=${CMAKE_MPI_FC_COMPILER}
      -D CMAKE_CXX_COMPILER=${CMAKE_MPI_CXX_COMPILER}
      -D CMAKE_C_FLAGS:STRING=${BUILD_SCALAPACK_C_FLAGS}
      -D CMAKE_Fortran_FLAGS:STRING=${BUILD_SCALAPACK_F_FLAGS}
      -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
      -D BLAS_LIBRARY_DIRS:STRING=${BLAS_DIR}
      -D LAPACK_LIBRARY_DIRS:STRING=${BLAS_DIR}
    DEPENDS_ON ${BLAS_PROJECT_NAME}
  )
  
  set(BLACS_DIR=${ScaLAPACK_DIR}/lib)
  
  list(APPEND DEALII_CONFOPTS "-D DEAL_II_WITH_SCALAPACK:BOOL=ON")
  list(APPEND DEALII_CONFOPTS "-D SCALAPACK_DIR=${ScaLAPACK_DIR}")

  list(APPEND TRILINOS_DEPENDENCIES "ScaLAPACK")
  list(APPEND TRILINOS_CONFOPTS "-D TPL_ENABLE_SCALAPACK:BOOL=ON")
  list(APPEND TRILINOS_CONFOPTS "-D SCALAPACK_LIBRARY_DIRS:PATH=${ScaLAPACK_DIR}/lib")
endmacro()