macro(build_superlu_dist)
  set(oneValueArgs VERSION)
  cmake_parse_arguments(BUILD_SUPERLU "" "${oneValueArgs}" "" ${ARGN})
  
  if (NOT BUILD_SUPERLU_VERSION)
    set(BUILD_SUPERLU_VERSION "5.1.2")
  endif()
  
  string(CONCAT BUILD_SUPERLU_REPO "https://github.com/xiaoyeli/" "superlu_dist.git")
  string(CONCAT BUILD_SUPERLU_TAG "v" ${BUILD_SUPERLU_VERSION})
  
  build_cmake_git_subproject(
    NAME SuperLU_DIST
    VERSION ${BUILD_SUPERLU_VERSION}
    GIT_REPO ${BUILD_SUPERLU_REPO}
    GIT_TAG ${BUILD_SUPERLU_TAG}
    DOWNLOAD_ONLY ${DOWNLOAD_ONLY}
    BUILD_ARGS
      -D TPL_PARMETIS_INCLUDE_DIRS:PATH=${ParMETIS_DIR}/include
      -D TPL_PARMETIS_LIBRARIES:PATH=${ParMETIS_LIB}
      -D TPL_BLAS_LIBRARIES=${BLAS_LIBS}
      -D TPL_ENABLE_LAPACKLIB=ON
      -D CMAKE_C_COMPILER=${CMAKE_MPI_C_COMPILER}
      -D CMAKE_CXX_COMPILER=${CMAKE_MPI_CXX_COMPILER}
      -D CMAKE_C_FLAGS:STRING=-fPIC      
      -D CMAKE_Fortran_FLAGS:STRING=-fPIC ${BLAS_Fortran_FLAGS}
      -D BUILD_SHARED_LIBS:BOOL=ON
    DEPENDS_ON ${BLAS_PROJECT_NAME} ParMETIS
  )
  
  list(APPEND TRILINOS_DEPENDENCIES "SuperLU_DIST")
  list(APPEND TRILINOS_CONFOPTS "-D TPL_ENABLE_SuperLUDist:BOOL=ON")
  list(APPEND TRILINOS_CONFOPTS "-D TPL_SuperLUDist_LIBRARIES:FILEPATH=${SuperLU_DIST_DIR}/lib/libsuperlu_dist${CMAKE_SHARED_LIBRARY_SUFFIX}")
  list(APPEND TRILINOS_CONFOPTS "-D SuperLUDist_INCLUDE_DIRS:PATH=${SuperLU_DIST_DIR}/include")
  list(APPEND TRILINOS_CONFOPTS "-D HAVE_SUPERLUDIST_LUSTRUCTINIT_2ARG:BOOL=ON")
  list(APPEND TRILINOS_CONFOPTS "-D HAVE_SUPERLUDIST_ENUM_NAMESPACE:BOOL=ON")
endmacro()